### ISSUE TITLE
rrd4j persistence NPE in receiveUpdate crashes notifyListeners thread

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab2#124]
upon restoration of values from the rrd4j persistence db at startup, the thread that handles notifyListeners() is exited, and as a consequence the rule engine stops to function (e.g. imho events are not triggered anymore). rrd4j jar version is 1.7.

09:31:05.003 [DEBUG] [o.e.s.m.p.i.PersistenceManager:377  ] - Restored item state from 'Feb 7, 2015 9:14:14 AM' for item 'BathroomKidsBlindCurrentPositionBlinds' -> '1'
09:31:05.081 [ERROR] [s.c.internal.items.ItemUpdater:95   ] - An error occured within the 'receiveUpdate' method of the event subscriber!java.lang.NullPointerException: null
	at org.eclipse.smarthome.core.items.GenericItem.notifyListeners(GenericItem.java:190)
	at org.eclipse.smarthome.core.items.GenericItem.setState(GenericItem.java:176)
	at org.eclipse.smarthome.core.internal.items.ItemUpdater.receiveUpdate(ItemUpdater.java:75)
	at org.eclipse.smarthome.core.events.AbstractEventSubscriber.receiveUpdate(AbstractEventSubscriber.java:166)
	at org.eclipse.smarthome.core.events.AbstractEventSubscriber.handleEvent(AbstractEventSubscriber.java:93)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

**Comment by kaikreuzer** [comment]
Should be fixed with https://github.com/eclipse/smarthome/pull/196, once this is available in openHAB 2.

**Comment by kaikreuzer** [comment]
The fix in ESH is now in the TP, so this problem should be solved.
