### ISSUE TITLE
compat1x: group item not handled by binding config

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab2#132]
Is there any reason why you have not supported group items for binding configuration?
I used this to create a group of items and delegate the same command to all of them.
This was a easy use case to switch all light that are members of this group.

<pre>
2015-02-16 13:04:02,872 | ERROR | FelixStartLevel  | GenericItemProvider              | 56 - org.eclipse.smarthome.model.item - 0.8.0.201502122129 | Binding configuration of type '...' of item ‘...‘ could not be parsed correctly.
org.eclipse.smarthome.model.item.BindingConfigParseException: cannot process unknown item type Group
        at org.openhab.core.binding.internal.BindingConfigReaderDelegate.getOpenHABItem(BindingConfigReaderDelegate.java:81)
        at org.openhab.core.binding.internal.BindingConfigReaderDelegate.getOpenHABItem(BindingConfigReaderDelegate.java:64)
        at org.openhab.core.binding.internal.BindingConfigReaderDelegate.validateItemType(BindingConfigReaderDelegate.java:39)
        at org.eclipse.smarthome.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:342)
        at org.eclipse.smarthome.model.item.internal.GenericItemProvider.dispatchBindingsPerType(GenericItemProvider.java:300)
        at org.eclipse.smarthome.model.item.internal.GenericItemProvider.addBindingConfigReader(GenericItemProvider.java:95)
</pre>

**Comment by kaikreuzer** [comment]
This should have been solved with https://github.com/openhab/openhab2/commit/60c3b883df39c567ce3f5cea8b17b972bca4cf93.
