### ISSUE TITLE
"Could not update status, because callback is missing" when new device added

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab2#210]
When a new device is discovered and auto added from the inbox, I'm getting the following exception -:

```code

20:11:41.797 [DEBUG] [b.z.h.ZigBeeCoordinatorHandler:151  ] - Browsing ZigBee network ...
20:11:41.799 [DEBUG] [.c.thing.internal.ThingManager:72   ] - Thing handler for thing 'zigbee:coordinator_cc2530:14cf1fdf47e' added.
20:11:41.799 [DEBUG] [.c.thing.internal.ThingManager:190  ] - Assigning handler for thing 'zigbee:coordinator_cc2530:14cf1fdf47e'.
20:11:41.800 [DEBUG] [.c.c.r.AbstractManagedProvider:62   ] - Added new element to ManagedThingProvider.
20:11:41.807 [DEBUG] [.c.c.r.AbstractManagedProvider:62   ] - Added new element to ManagedItemProvider.
20:11:41.813 [DEBUG] [.c.t.internal.ThingLinkManager:309  ] - Assigning linked group item 'zigbee_coordinator_cc2530_14cf1fdf47e' to thing 'zigbee:coordinator_cc2530:14cf1fdf47e'.
20:11:41.813 [DEBUG] [.c.c.r.AbstractManagedProvider:62   ] - Added new element to ManagedItemThingLinkProvider.
20:11:42.093 [WARN ] [b.z.n.d.ZigBeeDiscoveryManager:326  ] - No proxy for ZigBee device type 97 found with endpoint 00:17:88:01:00:DC:88:0B/242.
20:11:52.159 [DEBUG] [.c.thing.internal.ThingManager:141  ] - Thing status of thing zigbee:coordinator_cc2530:14cf1fdf47e changed: StatusInfo [getStatus()=ONLINE, getStatusDetail()=NONE, getDescription()=null]
20:11:52.161 [DEBUG] [b.z.h.ZigBeeCoordinatorHandler:176  ] - ZigBee network READY. Found 1 nodes.
20:11:52.161 [DEBUG] [b.z.h.ZigBeeCoordinatorHandler:182  ] - ZigBee 'Color Dimmable Light' device at address 00:17:88:01:00:DC:88:0B/11
20:11:52.161 [DEBUG] [b.z.h.ZigBeeCoordinatorHandler:357  ] - Device Discovery: 'Color Dimmable Light' 00:17:88:01:00:DC:88:0B/11 49246
20:11:52.161 [INFO ] [.z.a.c.impl.core.AttributeImpl:127  ] - Reading ManufacturerName from 00:17:88:01:00:DC:88:0B
20:11:52.198 [INFO ] [.z.a.c.impl.core.AttributeImpl:127  ] - Reading ModelIdentifier from 00:17:88:01:00:DC:88:0B
20:11:52.275 [DEBUG] [o.b.z.d.ZigBeeDiscoveryService:137  ] - Device discovery: 'Color Dimmable Light' 00:17:88:01:00:DC:88:0B/11 49246
20:11:52.275 [DEBUG] [o.b.z.d.ZigBeeDiscoveryService:120  ] - Using ThingUID: ColorDimmableLight
20:11:52.284 [DEBUG] [o.c.i.inbox.AutoApproveService:65   ] - Approving inbox entry 'DiscoveryResult [thingUID=zigbee:ColorDimmableLight:14cf1fdf47e:0017880100dc880b_11, properties={macAddress=00:17:88:01:00:DC:88:0B/11}, flag=NEW, label=Color Dimmable Light(Philips:LCT001), bridgeUID=zigbee:coordinator_cc2530:14cf1fdf47e, ttl=-1, timestamp=1429989112275]'
20:11:52.299 [DEBUG] [s.c.d.internal.PersistentInbox:252  ] - Discovery result removed from inbox, because it was added as a Thing to the ThingRegistry.
20:11:52.300 [DEBUG] [.c.thing.internal.ThingManager:277  ] - Thing 'zigbee:ColorDimmableLight:14cf1fdf47e:0017880100dc880b_11' is tracked by ThingManager.
20:11:52.300 [DEBUG] [.c.thing.internal.ThingManager:380  ] - Creating handler for thing 'zigbee:ColorDimmableLight:14cf1fdf47e:0017880100dc880b_11'.
20:11:52.300 [DEBUG] [o.o.b.z.i.ZigBeeHandlerFactory:45   ] - Creating handler for zigbee:ColorDimmableLight
20:11:52.320 [ERROR] [.c.thing.internal.ThingManager:389  ] - Exception occured while calling handler: Could not update status, because callback is missingjava.lang.IllegalStateException: Could not update status, because callback is missing
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateStatus(BaseThingHandler.java:288)
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateStatus(BaseThingHandler.java:315)
	at org.openhab.binding.zigbee.handler.ZigBeeLightHandler.bridgeHandlerInitialized(ZigBeeLightHandler.java:97)
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler$2.addingService(BaseThingHandler.java:101)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:318)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:261)
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.setBundleContext(BaseThingHandler.java:115)
```

I'm reasonably sure this used to work in the past - I thought that things actually went into the inbox and then had to be approved (has that changed or am I imagining it?).

My guess is that with the auto discovery and auto approve, something isn't initialised - it all works fine if I restart the binding, and as above, I'm pretty sure it used to work fine when auto approve was off.

This might be a bug in the ZigBee binding - I'm just not sure if there's anything that needs to be initialised before calling thingDiscovered? The link below is the offending line in the binding - maybe someone can take a quick look to see if I'm missing something, or maybe this is a timing issue with Auto Approve?

https://github.com/cdjackson/openhab2/blob/zigbee/addons/binding/org.openhab.binding.zigbee/src/main/java/org/openhab/binding/zigbee/discovery/ZigBeeDiscoveryService.java#L154

**Comment by kaikreuzer** [comment]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=465762.
Will be fixed with the next stable ESH build.

**Comment by kaikreuzer** [comment]
Fixed in latest build
