### ISSUE TITLE
Setting/Editing Properties gives error - ManagedProvider is not available

### ISSUE THREAD

**Issue by marcelrv** [openhab/openhab2#218]
When updating Thing properties at the initialization of a thing, there is an error  *ManagedProvider is not available*. If the same code is run later no error is generated.

The update is done using almost the example code

error:
```
00:23:44.775 [pool-5-thread-1] DEBUG o.o.b.m.i.h.MaxCubeBridgeHandler - java.lang.IllegalStateException: ManagedProvider is not available
        at org.eclipse.smarthome.core.common.registry.AbstractRegistry.update(AbstractRegistry.java:115)
        at org.eclipse.smarthome.core.thing.internal.ThingManager$1.thingUpdated(ThingManager.java:164)
        at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateProperties(BaseThingHandler.java:416)
        at org.openhab.binding.max.internal.handler.MaxCubeBridgeHandler.processMessage(MaxCubeBridgeHandler.java:479)
        at org.openhab.binding.max.internal.handler.MaxCubeBridgeHandler.refreshDeviceData(MaxCubeBridgeHandler.java:331)
        at org.openhab.binding.max.internal.handler.MaxCubeBridgeHandler.refreshData(MaxCubeBridgeHandler.java:236)
        at org.openhab.binding.max.internal.handler.MaxCubeBridgeHandler.access$0(MaxCubeBridgeHandler.java:233)
        at org.openhab.binding.max.internal.handler.MaxCubeBridgeHandler$1.run(MaxCubeBridgeHandler.java:136)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

```

code generating the error
```
	private void setProperties(H_Message message) {
		try {
			logger.debug ("MAX! Cube properties update");
			Map<String, String> properties = editProperties();
			properties.put(Thing.PROPERTY_MODEL_ID, DeviceType.Cube.toString());
			properties.put(Thing.PROPERTY_FIRMWARE_VERSION, message.getFirmwareVersion());
			properties.put(Thing.PROPERTY_SERIAL_NUMBER,message.getSerialNumber());
			properties.put(Thing.PROPERTY_VENDOR, MaxBinding.PROPERTY_VENDOR_NAME);
			properties.put(MaxBinding.PROPERTY_RFADDRESS,message.getRfHexAddress());			
			updateProperties(properties);
			for (Map.Entry<String, String> entry : properties.entrySet()){
				 logger.debug ("key: {}  : {}", entry.getKey(), entry.getValue());
			}
			logger.debug ("properties updated");
			propertiesSet = true;
		} catch (Exception e) {
			logger.debug("Exception occurred during property edit: {}", e.getMessage(), e);
		}
	}
```

**Comment by kaikreuzer** [comment]
Thanks, this is a startup behaviour bug in ESH, I have created an isue for it: https://bugs.eclipse.org/bugs/show_bug.cgi?id=465885

**Comment by kaikreuzer** [comment]
This has been fixed with https://github.com/eclipse/smarthome/pull/298, which should be available with the next build of https://openhab.ci.cloudbees.com/job/smarthome/
