### ISSUE TITLE
Rules doesn't work anymore after Upgrade

### ISSUE THREAD

**Issue by theArch2** [openhab/openhab2#224]
Hi, 

yesterday i updated my OpenHAB from 2.0.0-alpha1 to 2.0.0-snapshot
Now, the rules doesnt work anymore.
An example:
```
rule "some description"
when
    Item someRoom_funkhandsender_t1 changed to ON
then
    sendCommand(someRoom_schreibtischlampe, ON);
end

rule "some description 2"
when
    Item someRoom_funkhandsender_t2 changed to ON
then
    sendCommand(someRoom_schreibtischlampe, OFF);
end
```

Is there something i have missed?
In debug-mode i dont see any error-messages...

**Comment by maggu2810** [comment]
I realized that my rules are broken, too.
I updated ESH.

**Comment by maggu2810** [comment]
The condition "when System started" is working.
The condition "update" and "change to" does not work.

**Comment by maggu2810** [comment]
If I am using the Eclipse IDE and ESH, the rules are working.

**Comment by maggu2810** [comment]
Just adding some stuff to keep them somewhere until further inspection:

<pre>
==> org.eclipse.smarthome.model.rule.runtime.log <==
2015-05-05 16:31:16,134 | DEBUG | lixDispatchQueue | runtime                          | FrameworkEvent ERROR - org.eclipse.smarthome.model.rule.runtime
org.osgi.framework.ServiceException: ServiceFactory.getService() resulted in a cycle.
        at org.apache.felix.framework.ServiceRegistry.getService(ServiceRegistry.java:304)[org.apache.felix.framework-4.6.1.jar:]
        at org.apache.felix.framework.Felix.getService(Felix.java:3671)[org.apache.felix.framework-4.6.1.jar:]
        at org.apache.felix.framework.BundleContextImpl.getService(BundleContextImpl.java:470)[org.apache.felix.framework-4.6.1.jar:]
        at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.obtain(EventHandlerProxy.java:286)
        at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:407)
        at org.apache.felix.eventadmin.impl.tasks.SyncDeliverTasks.execute(SyncDeliverTasks.java:118)
        at org.apache.felix.eventadmin.impl.handler.EventAdminImpl.sendEvent(EventAdminImpl.java:147)
        at org.apache.felix.eventadmin.impl.security.EventAdminSecurityDecorator.sendEvent(EventAdminSecurityDecorator.java:96)
        at org.eclipse.smarthome.core.internal.events.EventPublisherImpl$1.run(EventPublisherImpl.java:70)
        at org.eclipse.smarthome.core.internal.events.EventPublisherImpl$1.run(EventPublisherImpl.java:1)
        at java.security.AccessController.doPrivileged(Native Method)[:1.7.0_60]
        at org.eclipse.smarthome.core.internal.events.EventPublisherImpl.sendCommand(EventPublisherImpl.java:67)
        at org.eclipse.smarthome.core.internal.events.EventPublisherImpl.sendCommand(EventPublisherImpl.java:169)
        at org.eclipse.smarthome.model.script.actions.BusEvent.sendCommand(BusEvent.java:95)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.7.0_60]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)[:1.7.0_60]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.7.0_60]
        at java.lang.reflect.Method.invoke(Method.java:606)[:1.7.0_60]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.invokeOperation(XbaseInterpreter.java:1084)
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.invokeOperation(XbaseInterpreter.java:1059)
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._invokeFeature(XbaseInterpreter.java:1045)
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.invokeFeature(XbaseInterpreter.java:990)
        at org.eclipse.smarthome.model.script.interpreter.ScriptInterpreter.invokeFeature(ScriptInterpreter.java:112)
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:762)
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:218)
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:202)
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:445)
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:226)
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:202)
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.evaluate(XbaseInterpreter.java:188)
        at org.eclipse.smarthome.model.script.runtime.internal.engine.ScriptImpl.execute(ScriptImpl.java:77)
        at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.runStartupRules(RuleEngineImpl.java:271)
        at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.activate(RuleEngineImpl.java:101)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.7.0_60]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)[:1.7.0_60]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.7.0_60]
        at java.lang.reflect.Method.invoke(Method.java:606)[:1.7.0_60]
        at org.apache.felix.scr.impl.helper.BaseMethod.invokeMethod(BaseMethod.java:231)[95:org.apache.felix.scr:1.8.2]
        at org.apache.felix.scr.impl.helper.BaseMethod.access$500(BaseMethod.java:39)[95:org.apache.felix.scr:1.8.2]
        at org.apache.felix.scr.impl.helper.BaseMethod$Resolved.invoke(BaseMethod.java:624)[95:org.apache.felix.scr:1.8.2]
        at org.apache.felix.scr.impl.helper.BaseMethod.invoke(BaseMethod.java:508)[95:org.apache.felix.scr:1.8.2]
        at org.apache.felix.scr.impl.helper.ActivateMethod.invoke(ActivateMethod.java:149)[95:org.apache.felix.scr:1.8.2]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:315)[95:org.apache.felix.scr:1.8.2]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:127)[95:org.apache.felix.scr:1.8.2]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:871)[95:org.apache.felix.scr:1.8.2]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:838)[95:org.apache.felix.scr:1.8.2]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:777)[95:org.apache.felix.scr:1.8.2]
        at org.apache.felix.framework.ServiceRegistrationImpl.getFactoryUnchecked(ServiceRegistrationImpl.java:343)[org.apache.felix.framework-4.6.1.jar:]
        at org.apache.felix.framework.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:243)[org.apache.felix.framework-4.6.1.jar:]
        at org.apache.felix.framework.ServiceRegistry.getService(ServiceRegistry.java:358)[org.apache.felix.framework-4.6.1.jar:]
        at org.apache.felix.framework.Felix.getService(Felix.java:3671)[org.apache.felix.framework-4.6.1.jar:]
        at org.apache.felix.framework.BundleContextImpl.getService(BundleContextImpl.java:470)[org.apache.felix.framework-4.6.1.jar:]
        at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:38)[124:com.eclipsesource.jaxrs.publisher:4.2.1.201502171315]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)[karaf-org.osgi.core.jar:]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)[karaf-org.osgi.core.jar:]
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)[karaf-org.osgi.core.jar:]
        at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)[karaf-org.osgi.core.jar:]
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:318)[karaf-org.osgi.core.jar:]
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:261)[karaf-org.osgi.core.jar:]
        at com.eclipsesource.jaxrs.publisher.internal.Activator.openAllServiceTracker(Activator.java:84)[124:com.eclipsesource.jaxrs.publisher:4.2.1.201502171315]
        at com.eclipsesource.jaxrs.publisher.internal.Activator.start(Activator.java:53)[124:com.eclipsesource.jaxrs.publisher:4.2.1.201502171315]
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)[org.apache.felix.framework-4.6.1.jar:]
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2223)[org.apache.felix.framework-4.6.1.jar:]
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2141)[org.apache.felix.framework-4.6.1.jar:]
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1368)[org.apache.felix.framework-4.6.1.jar:]
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)[org.apache.felix.framework-4.6.1.jar:]
        at java.lang.Thread.run(Thread.java:745)[:1.7.0_60]
</pre>

**Comment by maggu2810** [comment]
I removed my old container and created the same one but using Equinox instead of Felix.
The rules are now working.

* I do not know if the error above is an indication of what has been going on.
* I do not know if this is a bug in Felix or in the ESH bundles.

**Comment by kaikreuzer** [comment]
I've tried the setup of @theArch2 with the current build:
Added to demo.items
```
Switch someRoom_funkhandsender_t1
Switch someRoom_schreibtischlampe
```
added to demo.rules
```
rule "some description"
when
    Item someRoom_funkhandsender_t1 changed to ON
then
    sendCommand(someRoom_schreibtischlampe, ON);
end
```
Then used the console to post update events:
```
smarthome update someRoom_funkhandsender_t1 OFF
Update has been sent successfully.
osgi> 2015-05-12 22:36:54 [INFO ] [runtime.busevents             :27   ] - someRoom_funkhandsender_t1 state updated to OFF
smarthome update someRoom_funkhandsender_t1 ON
Update has been sent successfully.
osgi> 2015-05-12 22:36:56 [DEBUG] [.m.r.r.i.engine.RuleEngineImpl:292  ] - Executing rule 'some description'
2015-05-12 22:36:56 [INFO ] [runtime.busevents             :27   ] - someRoom_funkhandsender_t1 state updated to ON
2015-05-12 22:36:56 [INFO ] [runtime.busevents             :22   ] - someRoom_schreibtischlampe received command ON
```
Looks all as expected, so the issue seems to be solved. Please make sure, that your "funkhandsender" really posts updates and not commands - otherwise you should rather use "received command ON" in your rule as a trigger.
