### ISSUE TITLE
Build 190 - Creating a manual weather entry causes null exception

### ISSUE THREAD

**Issue by xsnrg** [openhab/openhab2#258]
reproduce in PaperUI, manually add a weather entry with a WOEID, the following exception happens.

2015-05-28 10:26:58.943 [ERROR] [.c.thing.internal.ThingManager] - Exception occured while calling handler: null
java.lang.NullPointerException: null
	at org.eclipse.smarthome.binding.yahooweather.handler.YahooWeatherHandler.startAutomaticRefresh(YahooWeatherHandler.java:101) ~[na:na]
	at org.eclipse.smarthome.binding.yahooweather.handler.YahooWeatherHandler.initialize(YahooWeatherHandler.java:75) ~[na:na]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandlerFactory.registerHandler(BaseThingHandlerFactory.java:116) ~[org.eclipse.smarthome.core.thing_0.8.0.201505251448.jar:na]
	at org.eclipse.smarthome.core.thing.internal.ThingManager.registerHandler(ThingManager.java:385) [org.eclipse.smarthome.core.thing_0.8.0.201505251448.jar:na]
	at org.eclipse.smarthome.core.thing.internal.ThingManager.registerHandler(ThingManager.java:352) [org.eclipse.smarthome.core.thing_0.8.0.201505251448.jar:na]
	at org.eclipse.smarthome.core.thing.internal.ThingManager.thingAdded(ThingManager.java:281) [org.eclipse.smarthome.core.thing_0.8.0.201505251448.jar:na]
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyTrackers(ThingRegistryImpl.java:154) [org.eclipse.smarthome.core.thing_0.8.0.201505251448.jar:na]
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutAddedElement(ThingRegistryImpl.java:75) [org.eclipse.smarthome.core.thing_0.8.0.201505251448.jar:na]
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutAddedElement(ThingRegistryImpl.java:1) [org.eclipse.smarthome.core.thing_0.8.0.201505251448.jar:na]
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.added(AbstractRegistry.java:50) [org.eclipse.smarthome.core_0.8.0.201505251448.jar:na]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:49) [org.eclipse.smarthome.core_0.8.0.201505251448.jar:na]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:68) [org.eclipse.smarthome.core_0.8.0.201505251448.jar:na]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListenersAboutAddedElement(AbstractProvider.java:72) [org.eclipse.smarthome.core_0.8.0.201505251448.jar:na]
	at org.eclipse.smarthome.core.common.registry.AbstractManagedProvider.add(AbstractManagedProvider.java:61) [org.eclipse.smarthome.core_0.8.0.201505251448.jar:na]
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.add(AbstractRegistry.java:104) [org.eclipse.smarthome.core_0.8.0.201505251448.jar:na]
	at org.eclipse.smarthome.core.thing.setup.ThingSetupManager.addThing(ThingSetupManager.java:497) [org.eclipse.smarthome.core.thing_0.8.0.201505251448.jar:na]
	at org.eclipse.smarthome.core.thing.setup.ThingSetupManager.addThing(ThingSetupManager.java:149) [org.eclipse.smarthome.core.thing_0.8.0.201505251448.jar:na]
	at org.eclipse.smarthome.core.thing.setup.ThingSetupManager.addThing(ThingSetupManager.java:118) [org.eclipse.smarthome.core.thing_0.8.0.201505251448.jar:na]
	at org.eclipse.smarthome.io.rest.core.thing.setup.ThingSetupManagerResource.addThing(ThingSetupManagerResource.java:68) [org.eclipse.smarthome.io.rest.core_0.8.0.201505251448.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [com.eclipsesource.jaxrs.jersey-all_2.17.0.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:164) [com.eclipsesource.jaxrs.jersey-all_2.17.0.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:181) [com.eclipsesource.jaxrs.jersey-all_2.17.0.jar:na]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:158) [com.eclipsesource.jaxrs.jersey-all_2.17.0.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:101) [com.eclipsesource.jaxrs.jersey-all_2.17.0.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [com.eclipsesource.jaxrs.jersey-all_2.17.0.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [com.eclipsesource.jaxrs.jersey-all_2.17.0.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [com.eclipsesource.jaxrs.jersey-all_2.17.0.jar:na]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:305) [com.eclipsesource.jaxrs.jersey-all_2.17.0.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [com.eclipsesource.jaxrs.jersey-all_2.17.0.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [com.eclipsesource.jaxrs.jersey-all_2.17.0.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [com.eclipsesource.jaxrs.jersey-all_2.17.0.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [com.eclipsesource.jaxrs.jersey-all_2.17.0.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [com.eclipsesource.jaxrs.jersey-all_2.17.0.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [com.eclipsesource.jaxrs.jersey-all_2.17.0.jar:na]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:288) [com.eclipsesource.jaxrs.jersey-all_2.17.0.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1110) [com.eclipsesource.jaxrs.jersey-all_2.17.0.jar:na]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:401) [com.eclipsesource.jaxrs.jersey-all_2.17.0.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386) [com.eclipsesource.jaxrs.jersey-all_2.17.0.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:335) [com.eclipsesource.jaxrs.jersey-all_2.17.0.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:222) [com.eclipsesource.jaxrs.jersey-all_2.17.0.jar:na]
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) [org.eclipse.equinox.http.servlet_1.1.500.v20140318-1755.jar:na]
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) [org.eclipse.equinox.http.servlet_1.1.500.v20140318-1755.jar:na]
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68) [org.eclipse.equinox.http.servlet_1.1.500.v20140318-1755.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet_3.1.0.v20140303-1611.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808) [org.eclipse.jetty.servlet_9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587) [org.eclipse.jetty.servlet_9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221) [org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [org.eclipse.jetty.servlet_9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215) [org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) [org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.Server.handle(Server.java:497) [org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [org.eclipse.jetty.io_9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [org.eclipse.jetty.util_9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [org.eclipse.jetty.util_9.2.9.v20150224.jar:9.2.9.v20150224]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]

**Comment by xsnrg** [comment]
I am using a label "Urbandale Weather" and a WOEID of 2510443

**Comment by kaikreuzer** [comment]
As build 190 is no longer available, I just tried to reproduce with build 191, but failed. That is to say: Everything worked as expected.
Can you confirm that the problem still exists? Is it 100% reproducible or does it only happen from time to time?

**Comment by xsnrg** [comment]
I am now running 191 as well, and am in a state where I will get this exception on startup every time I start OpenHAB2.   I will try removing the thing, restarting to make sure the exception is gone, and add it again to see what happens.

2015-05-29 16:17:26.085 [INFO ] [ui.internal.servlet.PaperUIApp] - Started Paper UI at /ui
2015-05-29 16:17:26.236 [ERROR] [.c.thing.internal.ThingManager] - Exception occured while calling handler: null
java.lang.NullPointerException: null
	at org.eclipse.smarthome.binding.yahooweather.handler.YahooWeatherHandler.startAutomaticRefresh(YahooWeatherHandler.java:101) ~[na:na]
	at org.eclipse.smarthome.binding.yahooweather.handler.YahooWeatherHandler.initialize(YahooWeatherHandler.java:75) ~[na:na]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandlerFactory.registerHandler(BaseThingHandlerFactory.java:116) ~[org.eclipse.smarthome.core.thing_0.8.0.201505281707.jar:na]
	at org.eclipse.smarthome.core.thing.internal.ThingManager.registerHandler(ThingManager.java:385) [org.eclipse.smarthome.core.thing_0.8.0.201505281707.jar:na]
	at org.eclipse.smarthome.core.thing.internal.ThingManager.addThingHandlerFactory(ThingManager.java:424) [org.eclipse.smarthome.core.thing_0.8.0.201505281707.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at org.eclipse.equinox.internal.ds.model.ComponentReference.bind(ComponentReference.java:376) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bindReference(ServiceComponentProp.java:444) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.InstanceProcess.dynamicBind(InstanceProcess.java:416) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:334) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109) [org.eclipse.osgi_3.10.2.v20150203-1939.jar:na]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:914) [org.eclipse.osgi_3.10.2.v20150203-1939.jar:na]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi_3.10.2.v20150203-1939.jar:na]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) [org.eclipse.osgi_3.10.2.v20150203-1939.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862) [org.eclipse.osgi_3.10.2.v20150203-1939.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801) [org.eclipse.osgi_3.10.2.v20150203-1939.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127) [org.eclipse.osgi_3.10.2.v20150203-1939.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225) [org.eclipse.osgi_3.10.2.v20150203-1939.jar:na]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:464) [org.eclipse.osgi_3.10.2.v20150203-1939.jar:na]
	at org.eclipse.equinox.internal.ds.InstanceProcess.registerService(InstanceProcess.java:536) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:213) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]

**Comment by xsnrg** [comment]
Trying to remove the thing through PaperUI gives:

osgi> 2015-05-29 16:23:44 [WARN ] [e.jetty.servlet.ServletHandler:620  ] - javax.servlet.ServletException: java.lang.NullPointerException
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:421)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:335)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:222)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
Caused by: java.lang.NullPointerException: null
	at org.eclipse.smarthome.core.items.ManagedItemProvider.remove(ManagedItemProvider.java:75)
	at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.remove(ItemRegistryImpl.java:381)
	at org.eclipse.smarthome.core.thing.setup.ThingSetupManager.removeThing(ThingSetupManager.java:362)
	at org.eclipse.smarthome.io.rest.core.thing.setup.ThingSetupManagerResource.removeThing(ThingSetupManagerResource.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:164)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:181)

2015-05-29 16:23:44 [WARN ] [lipse.jetty.server.HttpChannel:395  ] - /rest/setup/things/yahooweather:weather:Urbandalejavax.servlet.ServletException: javax.servlet.ServletException: java.lang.NullPointerException
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:130)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.servlet.ServletException: java.lang.NullPointerException
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:421)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:335)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:222)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
Caused by: java.lang.NullPointerException: null
	at org.eclipse.smarthome.core.items.ManagedItemProvider.remove(ManagedItemProvider.java:75)
	at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.remove(ItemRegistryImpl.java:381)
	at org.eclipse.smarthome.core.thing.setup.ThingSetupManager.removeThing(ThingSetupManager.java:362)
	at org.eclipse.smarthome.io.rest.core.thing.setup.ThingSetupManagerResource.removeThing(ThingSetupManagerResource.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:164)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:181)

2015-05-29 16:23:44 [WARN ] [lipse.jetty.server.HttpChannel:481  ] - Could not send response error 500: javax.servlet.ServletException: javax.servlet.ServletException: java.lang.NullPointerException

**Comment by xsnrg** [comment]
removing from command line works:

osgi> smarthome things remove yahooweather:weather:9d8813a9
2015-05-29 16:24:54 [DEBUG] [.c.t.internal.ThingLinkManager:319  ] - Removing linked item 'yahooweather_weather_9d8813a9_temperature' from channel 'yahooweather:weather:9d8813a9:temperature'.
2015-05-29 16:24:54 [DEBUG] [.c.t.internal.ThingLinkManager:319  ] - Removing linked item 'yahooweather_weather_9d8813a9_humidity' from channel 'yahooweather:weather:9d8813a9:humidity'.
2015-05-29 16:24:54 [DEBUG] [.c.t.internal.ThingLinkManager:319  ] - Removing linked item 'yahooweather_weather_9d8813a9_pressure' from channel 'yahooweather:weather:9d8813a9:pressure'.
2015-05-29 16:24:54 [DEBUG] [.c.thing.internal.ThingManager:305  ] - Thing 'yahooweather:weather:9d8813a9' is no longer tracked by ThingManager.
2015-05-29 16:24:54 [DEBUG] [.c.c.r.AbstractManagedProvider:115  ] - Removed element from ManagedThingProvider.
Thing 'yahooweather:weather:9d8813a9' successfully removed.

**Comment by xsnrg** [comment]
I lied.  It won't remove all of it:

osgi> smarthome things
yahooweather:weather:Urbandale (Type=Thing, Status=ONLINE, Bridge=null)
hue:LCT001:c2c51210:7 (Type=Thing, Status=ONLINE, Bridge=hue:bridge:c2c51210)
hue:bridge:c2c51210 (Type=Bridge, Status=ONLINE, Bridge=null)
network:device:192_168_1_161 (Type=Thing, Status=ONLINE, Bridge=null)
sonos:zoneplayer:RINCON_B8E93721C7F801400 (Type=Thing, Status=ONLINE, Bridge=null)
osgi> smarthome things remove yahooweather:weather:Urbandale
Could not delete thing yahooweather:weather:Urbandale.

**Comment by kaikreuzer** [comment]
> Could not delete thing yahooweather:weather:Urbandale.

You obviously cannot delete Things that you define in a file (and not having added through the UI). I guess this is here the case?

**Comment by xsnrg** [comment]
Build 192, problem persists.  I have no things in config files in this install.  I simply fire up OH2, go to paper UI, it does it's auto-find based on geoIP, which is off for me based on ISP, but to be expected, so I remove that one, and add one manually through paperUI.  When I add it, I get the exception every time.  Note that I am changing 3 things.  I change the name to match the WOEID, that is, if I am using the WOEID for Urbandale, then I am changing the name to say Urbandale weather.  I am changing the refresh from 60 to 120, and I am putting in the WOEID.

yahooweather:weather:f02a363a (Type=Thing, Status=UNINITIALIZED (HANDLER_INITIALIZING_ERROR), Bridge=null)

**Comment by kaikreuzer** [comment]
Thanks @xsnrg, I have tracked that down to an error in the Paper UI - I have created issue https://github.com/openhab/smarthome/issues/15 for it.

**Comment by xsnrg** [comment]
@kaikreuzer , this seems to be working now, though I didn't see the ticket get worked.  Perhaps another fix took care of this as well.  Closing.

**Comment by kaikreuzer** [comment]
The referenced issue was indeed fixed (only the link is now broken since we moved the repo).
