### ISSUE TITLE
SystemInfoBinding 1.7 throwing error on OH2 Alpha 2

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab2#259]
2015-05-29 15:28:20 [ERROR] [b.s.internal.SysteminfoBinding:436  ] - System monitor error: {}org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Sigar.getNetInterfaceList()[Ljava/lang/String;
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy49.getNetInterfaceList(Unknown Source)
	at org.openhab.binding.systeminfo.internal.SysteminfoBinding.initializeSystemMonitor(SysteminfoBinding.java:419)
	at org.openhab.binding.systeminfo.internal.SysteminfoBinding.updated(SysteminfoBinding.java:403)
	at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:276)
	at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36)

2015-05-29 15:28:20 [INFO ] [.service.AbstractActiveService:169  ] - Systeminfo Refresh Service has been started

**Comment by kaikreuzer** [comment]
Could you report this at openHAB 1 as this binding is maintained there?
