### ISSUE TITLE
alpha2 demo throws java.net.URISyntaxException in jetty

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab2#261]
Unzipping the release .zip and starting up:

2015-05-29 22:02:41 [WARN ] [e.jetty.util.resource.Resource:121  ] - java.net.URISyntaxException: Illegal character in path at index 41: file:/Users/kgoderis/Documents/openHAB2.0 alpha2/runtime/server/configuration/org.eclipse.osgi/126/0/.cp/jettyhome/etc/jetty.xml
2015-05-29 22:02:41 [WARN ] [.o.b.i.s.ServerInstanceWrapper:157  ] - File does not exist file:/Users/kgoderis/Documents/openHAB2.0 alpha2/runtime/server/configuration/org.eclipse.osgi/126/0/.cp/jettyhome/etc/jetty.xml; BadResource=java.net.URISyntaxException: Illegal character in path at index 41: file:/Users/kgoderis/Documents/openHAB2.0 alpha2/runtime/server/configuration/org.eclipse.osgi/126/0/.cp/jettyhome/etc/jetty.xml
java.lang.IllegalStateException: No such jetty server config file: file:/Users/kgoderis/Documents/openHAB2.0 alpha2/runtime/server/configuration/org.eclipse.osgi/126/0/.cp/jettyhome/etc/jetty.xml; BadResource=java.net.URISyntaxException: Illegal character in path at index 41: file:/Users/kgoderis/Documents/openHAB2.0 alpha2/runtime/server/configuration/org.eclipse.osgi/126/0/.cp/jettyhome/etc/jetty.xml
	at org.eclipse.jetty.osgi.boot.internal.serverfactory.ServerInstanceWrapper.configure(ServerInstanceWrapper.java:158)
	at org.eclipse.jetty.osgi.boot.internal.serverfactory.DefaultJettyAtJettyHomeHelper.startJettyAtJettyHome(DefaultJettyAtJettyHomeHelper.java:173)
	at org.eclipse.jetty.osgi.boot.JettyBootstrapActivator.start(JettyBootstrapActivator.java:93)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:936)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:319)
	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
	at org.eclipse.osgi.container.Module.start(Module.java:439)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

**Comment by kgoderis** [comment]
Found it : it is not allowed to have a space in the folder name where OH is residing

**Comment by kaikreuzer** [comment]
Hey, this is even written in the very first line of the installation instructions: https://github.com/openhab/openhab2/blob/master/docs/sources/installation/runtime.md#installation-of-openhab-2 <https://github.com/openhab/openhab2/blob/master/docs/sources/installation/runtime.md#installation-of-openhab-2>

**Comment by kgoderis** [comment]
Yeah yeah - I read those a very very long time ago.
