### ISSUE TITLE
Philips Hue binding: Paper UI lacks pairing notification ("press button on Hue hub")

### ISSUE THREAD

**Issue by WetwareLabs** [openhab/openhab2#302]
I'm using nightly build 14.7.2015 with JRE 1.8.45. 

When trying the Paper UI with demo configuration, Philips Hue hub was automatically detected, but no lights were found. 

Cause: Hue binding waits for the user to press pairing button on Hue hub, but no notification of this action required is shown on Paper UI. Then UI silently fails, but recovers when the button is pressed.

Log:
```
2015-07-14 19:56:36.341 [INFO ] [ome.event.ThingStatusInfoEvent] - hue:bridge:0017881a90f0' updated: INITIALIZING
2015-07-14 19:56:36.415 [INFO ] [marthome.event.ThingAddedEvent] - Thing 'hue:bridge:0017881a90f0' has been added.
2015-07-14 19:56:36.476 [INFO ] [smarthome.event.ItemAddedEvent] - Item 'hue_bridge_0017881a90f0' has been added.
2015-07-14 19:56:36.731 [INFO ] [b.hue.handler.HueBridgeHandler] - Hue bridge 192.168.1.81 is not authenticated - please press the pairing button on the bridge.
2015-07-14 19:56:36.762 [ERROR] [b.hue.handler.HueBridgeHandler] - Bridge cannot search for new lights.
java.lang.IllegalStateException: linking is required before interacting with the bridge
	at nl.q42.jue.HueBridge.requireAuthentication(HueBridge.java:783) ~[jue.jar:na]
	at nl.q42.jue.HueBridge.getFullConfig(HueBridge.java:771) ~[jue.jar:na]
	at org.eclipse.smarthome.binding.hue.handler.HueBridgeHandler.getFullLights(HueBridgeHandler.java:345) ~[bundleFile:na]
	at org.eclipse.smarthome.binding.hue.internal.discovery.HueLightDiscoveryService.startScan(HueLightDiscoveryService.java:71) [bundleFile:na]
	at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.startScan(AbstractDiscoveryService.java:196) [org.eclipse.smarthome.config.discovery_0.8.0.201507090807.jar:na]
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScan(DiscoveryServiceRegistryImpl.java:316) [org.eclipse.smarthome.config.discovery_0.8.0.201507090807.jar:na]
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScans(DiscoveryServiceRegistryImpl.java:293) [org.eclipse.smarthome.config.discovery_0.8.0.201507090807.jar:na]
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScan(DiscoveryServiceRegistryImpl.java:170) [org.eclipse.smarthome.config.discovery_0.8.0.201507090807.jar:na]
	at org.eclipse.smarthome.io.rest.core.discovery.DiscoveryResource.scan(DiscoveryResource.java:64) [org.eclipse.smarthome.io.rest.core_0.8.0.201507090807.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:403) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76) [com.eclipsesource.jaxrs.publisher_5.0.0.201506221200.jar:na]
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) [org.eclipse.equinox.http.servlet_1.1.500.v20140318-1755.jar:na]
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) [org.eclipse.equinox.http.servlet_1.1.500.v20140318-1755.jar:na]
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68) [org.eclipse.equinox.http.servlet_1.1.500.v20140318-1755.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet_3.1.0.v20140303-1611.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808) [org.eclipse.jetty.servlet_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587) [org.eclipse.jetty.servlet_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221) [org.eclipse.jetty.server_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [org.eclipse.jetty.server_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [org.eclipse.jetty.servlet_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [org.eclipse.jetty.server_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [org.eclipse.jetty.server_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [org.eclipse.jetty.server_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215) [org.eclipse.jetty.server_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) [org.eclipse.jetty.server_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [org.eclipse.jetty.server_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.server.Server.handle(Server.java:497) [org.eclipse.jetty.server_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [org.eclipse.jetty.server_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [org.eclipse.jetty.server_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [org.eclipse.jetty.io_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [org.eclipse.jetty.util_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [org.eclipse.jetty.util_9.2.10.v20150310.jar:9.2.10.v20150310]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
2015-07-14 19:56:36.773 [ERROR] [b.hue.handler.HueBridgeHandler] - Bridge cannot start search mode
java.lang.IllegalStateException: linking is required before interacting with the bridge
	at nl.q42.jue.HueBridge.requireAuthentication(HueBridge.java:783) ~[jue.jar:na]
	at nl.q42.jue.HueBridge.startSearch(HueBridge.java:155) ~[jue.jar:na]
	at org.eclipse.smarthome.binding.hue.handler.HueBridgeHandler.startSearch(HueBridgeHandler.java:357) ~[bundleFile:na]
	at org.eclipse.smarthome.binding.hue.internal.discovery.HueLightDiscoveryService.startScan(HueLightDiscoveryService.java:78) [bundleFile:na]
	at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.startScan(AbstractDiscoveryService.java:196) [org.eclipse.smarthome.config.discovery_0.8.0.201507090807.jar:na]
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScan(DiscoveryServiceRegistryImpl.java:316) [org.eclipse.smarthome.config.discovery_0.8.0.201507090807.jar:na]
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScans(DiscoveryServiceRegistryImpl.java:293) [org.eclipse.smarthome.config.discovery_0.8.0.201507090807.jar:na]
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScan(DiscoveryServiceRegistryImpl.java:170) [org.eclipse.smarthome.config.discovery_0.8.0.201507090807.jar:na]
	at org.eclipse.smarthome.io.rest.core.discovery.DiscoveryResource.scan(DiscoveryResource.java:64) [org.eclipse.smarthome.io.rest.core_0.8.0.201507090807.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:403) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221) [com.eclipsesource.jaxrs.jersey-min_2.18.0.jar:na]
	at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76) [com.eclipsesource.jaxrs.publisher_5.0.0.201506221200.jar:na]
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) [org.eclipse.equinox.http.servlet_1.1.500.v20140318-1755.jar:na]
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) [org.eclipse.equinox.http.servlet_1.1.500.v20140318-1755.jar:na]
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68) [org.eclipse.equinox.http.servlet_1.1.500.v20140318-1755.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet_3.1.0.v20140303-1611.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808) [org.eclipse.jetty.servlet_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587) [org.eclipse.jetty.servlet_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221) [org.eclipse.jetty.server_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [org.eclipse.jetty.server_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [org.eclipse.jetty.servlet_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [org.eclipse.jetty.server_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [org.eclipse.jetty.server_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [org.eclipse.jetty.server_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215) [org.eclipse.jetty.server_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) [org.eclipse.jetty.server_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [org.eclipse.jetty.server_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.server.Server.handle(Server.java:497) [org.eclipse.jetty.server_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [org.eclipse.jetty.server_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [org.eclipse.jetty.server_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [org.eclipse.jetty.io_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [org.eclipse.jetty.util_9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [org.eclipse.jetty.util_9.2.10.v20150310.jar:9.2.10.v20150310]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
2015-07-14 19:56:37.451 [INFO ] [b.hue.handler.HueBridgeHandler] - Hue bridge 192.168.1.81 is not authenticated - please press the pairing button on the bridge.
2015-07-14 19:56:47.424 [INFO ] [b.hue.handler.HueBridgeHandler] - Hue bridge 192.168.1.81 is not authenticated - please press the pairing button on the bridge.
2015-07-14 19:56:57.414 [INFO ] [b.hue.handler.HueBridgeHandler] - Hue bridge 192.168.1.81 is not authenticated - please press the pairing button on the bridge.
2015-07-14 19:57:07.413 [INFO ] [b.hue.handler.HueBridgeHandler] - Hue bridge 192.168.1.81 is not authenticated - please press the pairing button on the bridge.
2015-07-14 19:57:17.431 [INFO ] [b.hue.handler.HueBridgeHandler] - Hue bridge 192.168.1.81 is not authenticated - please press the pairing button on the bridge.
2015-07-14 19:57:26.966 [INFO ] [ome.event.ThingStatusInfoEvent] - yahooweather:weather:berlin' updated: ONLINE
2015-07-14 19:57:26.972 [INFO ] [smarthome.event.ItemStateEvent] - Weather_Temperature updated to 18
2015-07-14 19:57:27.415 [INFO ] [b.hue.handler.HueBridgeHandler] - Hue bridge 192.168.1.81 is not authenticated - please press the pairing button on the bridge.
2015-07-14 19:57:37.413 [INFO ] [b.hue.handler.HueBridgeHandler] - Hue bridge 192.168.1.81 is not authenticated - please press the pairing button on the bridge.
2015-07-14 19:57:47.414 [INFO ] [b.hue.handler.HueBridgeHandler] - Hue bridge 192.168.1.81 is not authenticated - please press the pairing button on the bridge.
.
.
.
.
2015-07-14 19:58:57.470 [INFO ] [b.hue.handler.HueBridgeHandler] - User 'EclipseSmartHome' has been successfully added to Hue bridge.
```

**Comment by kaikreuzer** [comment]
The exception had been addressed with https://github.com/eclipse/smarthome/pull/382.

https://github.com/eclipse/smarthome/pull/410 will make sure (once it is merged and published to openHAB 2) that the bridge goes to offline with an according message, which will be shown in the UI like this:
<img width="1011" alt="bildschirmfoto 2015-07-30 um 17 25 03" src="https://cloud.githubusercontent.com/assets/3244965/8987168/f91b1dc6-36df-11e5-8a68-6915cc9b347d.png">

**Comment by dnobel** [comment]
PR was merged.
