### ISSUE TITLE
Freebox binding 2.0 | Getting a "500" error, freebox not requesting authentication validation

### ISSUE THREAD

**Issue by jsiobj** [openhab/openhab2#305]
Hello,

I am quite new to OpenHAB2 and trying to get it up and running on a Rapsberry Pi 2. 

When trying to a a Freebox thing, when saving the config for the first time, I get a 500 error on the bottom left of Paper UI, application token stay desperately empty, freebox does not ask for authentication validation and freebox thing status in openHAB2 is "initializing".

I get the following warning in openHAB2 console : 
```
2015-07-16 22:36:04 [WARN ] [lipse.jetty.server.HttpChannel:481  ] - Could not send response error 500: javax.servlet.ServletException: javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: com/google/common/base/Function
```

If I click on the validation button again, it treates the thing but it stays in "uninitialized" state.

I just downloaded latest build from CloudBees (build #265)

Am I missing a pre-requisite on my Pi ?

Thank you in anticipation for your help.
JS

**Comment by kaikreuzer** [comment]
@clinique Could you have a look?

**Comment by clinique** [comment]
Sorry, not in France currently - will be able to take a look start of september.

**Comment by kaikreuzer** [comment]
> will be able to take a look start of september.

@clinique, Which year? ;-)

**Comment by clinique** [comment]
Sorry, moved to Spain, no access to the equipment currently.

**Comment by jsiobj** [comment]
Hello @clinique,

I looked into logs and saw this error : 

```
2015-09-26 00:14:37 [ERROR] [.c.thing.internal.ThingManager:504  ] - Exception occured while calling thing handler factory 'org.openhab.binding.freebox.internal.FreeboxHandlerFactory@128e799': com/google/common/base/Functionjava.lang.NoClassDefFoundError: com/google/common/base/Function
        at org.matmaul.freeboxos.FreeboxOsClient.<init>(FreeboxOsClient.java:55)
        at org.openhab.binding.freebox.handler.FreeboxHandler.authorize(FreeboxHandler.java:97)
        at org.openhab.binding.freebox.handler.FreeboxHandler.initialize(FreeboxHandler.java:145)
        at org.eclipse.smarthome.core.thing.binding.BaseThingHandlerFactory.registerHandler(BaseThingHandlerFactory.java:116)
        at org.eclipse.smarthome.core.thing.internal.ThingManager$6.call(ThingManager.java:495)
        at org.eclipse.smarthome.core.thing.internal.ThingManager$6.call(ThingManager.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Function cannot be found by org.openhab.binding.freebox_2.0.0.201509190234
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.matmaul.freeboxos.FreeboxOsClient.<init>(FreeboxOsClient.java:55)
        at org.openhab.binding.freebox.handler.FreeboxHandler.authorize(FreeboxHandler.java:97)
        at org.openhab.binding.freebox.handler.FreeboxHandler.initialize(FreeboxHandler.java:145)
        at org.eclipse.smarthome.core.thing.binding.BaseThingHandlerFactory.registerHandler(BaseThingHandlerFactory.java:116)
        at org.eclipse.smarthome.core.thing.internal.ThingManager$6.call(ThingManager.java:495)
        at org.eclipse.smarthome.core.thing.internal.ThingManager$6.call(ThingManager.java:1)
```

Is there anything obvious I could look at ? Am I missing some prerequisite ?

Thanks.
JS

**Comment by kaikreuzer** [comment]
Looks as if an import-package is missing in the binding. I have added it here now: https://github.com/openhab/openhab2/pull/395/files

Please have a try with the next build (https://openhab.ci.cloudbees.com/job/openHAB2/344/), once this is through.

**Comment by jsiobj** [comment]
Working ! I got openHAB authenticated to my freebox :-)
Thanks a lot. I'll continue my testings then.

**Comment by kaikreuzer** [comment]
Perfect!
