### ISSUE TITLE
IDE Setup with eclipse-installer not working

### ISSUE THREAD

**Issue by jotwg** [openhab/openhab2#315]
Hi,

trying to install the ide on Windows 7, java 8:

eclipse.buildId=4.5.0.I20150603-2000
java.version=1.8.0_51
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product -data D:\Projects\openhab2-master\ws

org.codehaus.groovy.eclipse.dsl
Error
Mon Jul 27 21:48:34 CEST 2015
C:\Users\jwg\.p2\pool\plugins\org.codehaus.groovy_2.3.10.xx-201507131633-e45\plugin_dsld_support\ does not exist

Java Model Exception: Java Model Status [C:\Users\jwg\.p2\pool\plugins\org.codehaus.groovy_2.3.10.xx-201507131633-e45\plugin_dsld_support\ does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:587)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
	at org.eclipse.jdt.internal.core.Openable.open(Openable.java:433)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob$DSLDResourceVisitor.findDSLDsInLibraries(RefreshDSLDJob.java:135)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob$DSLDResourceVisitor.findFiles(RefreshDSLDJob.java:96)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob.refreshProject(RefreshDSLDJob.java:379)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob.run(RefreshDSLDJob.java:317)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by kaikreuzer** [comment]
Does it mean that the IDE does not even start and this is your log?
Did you try a second time to see if it is reproducible?

**Comment by jotwg** [comment]
sorry, my description is actually a bit "brief"....

Seems that I had have issues with my java installation. After a reinstallation of jdk 1.7 the eclipse installer terminates without any complaints and eclipse starts and performs the startup task succesfully now. Though, the warnings regarding lastModified <= 0 and the errors complaining about missing groovy stuff are still there in the error log (see below). Nevertheless, build of all bundles is successful and I think you can close this issue.
Still remaing are a number of "Could not bind a reference..." messages when the openhab runtime starts up (see console log below), but I think this is a different story.

Thx! 

----------- error log -------------------------------
!SESSION 2015-07-28 19:13:12.456 -----------------------------------------------
eclipse.buildId=4.5.0.I20150603-2000
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product -data D:\Projects\openhab2-master\ws

!ENTRY org.codehaus.groovy.eclipse.dsl 4 0 2015-07-28 19:14:29.890
!MESSAGE C:\Users\jwg\.groovy\greclipse\global_dsld_support does not exist
!STACK 1
Java Model Exception: Java Model Status [C:\Users\jwg\.groovy\greclipse\global_dsld_support does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:587)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
	at org.eclipse.jdt.internal.core.Openable.open(Openable.java:433)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob$DSLDResourceVisitor.findDSLDsInLibraries(RefreshDSLDJob.java:135)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob$DSLDResourceVisitor.findFiles(RefreshDSLDJob.java:96)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob.refreshProject(RefreshDSLDJob.java:379)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob.run(RefreshDSLDJob.java:317)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
!SUBENTRY 1 org.eclipse.jdt.core 4 969 2015-07-28 19:14:29.892
!MESSAGE C:\Users\jwg\.groovy\greclipse\global_dsld_support does not exist

!ENTRY org.codehaus.groovy.eclipse.dsl 4 0 2015-07-28 19:14:29.927
!MESSAGE C:\Users\jwg\.p2\pool\plugins\org.codehaus.groovy_2.3.10.xx-201507131633-e45\plugin_dsld_support\ does not exist
!STACK 1
Java Model Exception: Java Model Status [C:\Users\jwg\.p2\pool\plugins\org.codehaus.groovy_2.3.10.xx-201507131633-e45\plugin_dsld_support\ does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:587)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
	at org.eclipse.jdt.internal.core.Openable.open(Openable.java:433)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob$DSLDResourceVisitor.findDSLDsInLibraries(RefreshDSLDJob.java:135)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob$DSLDResourceVisitor.findFiles(RefreshDSLDJob.java:96)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob.refreshProject(RefreshDSLDJob.java:379)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob.run(RefreshDSLDJob.java:317)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
!SUBENTRY 1 org.eclipse.jdt.core 4 969 2015-07-28 19:14:29.927
!MESSAGE C:\Users\jwg\.p2\pool\plugins\org.codehaus.groovy_2.3.10.xx-201507131633-e45\plugin_dsld_support\ does not exist

!ENTRY org.codehaus.groovy.eclipse.dsl 4 0 2015-07-28 19:14:30.685
!MESSAGE C:\Users\jwg\.groovy\greclipse\global_dsld_support does not exist
!STACK 1
Java Model Exception: Java Model Status [C:\Users\jwg\.groovy\greclipse\global_dsld_support does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:587)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
	at org.eclipse.jdt.internal.core.Openable.open(Openable.java:433)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob$DSLDResourceVisitor.findDSLDsInLibraries(RefreshDSLDJob.java:135)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob$DSLDResourceVisitor.findFiles(RefreshDSLDJob.java:96)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob.refreshProject(RefreshDSLDJob.java:379)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob.run(RefreshDSLDJob.java:317)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
!SUBENTRY 1 org.eclipse.jdt.core 4 969 2015-07-28 19:14:30.685
!MESSAGE C:\Users\jwg\.groovy\greclipse\global_dsld_support does not exist

!ENTRY org.codehaus.groovy.eclipse.dsl 4 0 2015-07-28 19:14:30.687
!MESSAGE C:\Users\jwg\.p2\pool\plugins\org.codehaus.groovy_2.3.10.xx-201507131633-e45\plugin_dsld_support\ does not exist
!STACK 1
Java Model Exception: Java Model Status [C:\Users\jwg\.p2\pool\plugins\org.codehaus.groovy_2.3.10.xx-201507131633-e45\plugin_dsld_support\ does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:587)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
	at org.eclipse.jdt.internal.core.Openable.open(Openable.java:433)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob$DSLDResourceVisitor.findDSLDsInLibraries(RefreshDSLDJob.java:135)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob$DSLDResourceVisitor.findFiles(RefreshDSLDJob.java:96)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob.refreshProject(RefreshDSLDJob.java:379)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob.run(RefreshDSLDJob.java:317)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
!SUBENTRY 1 org.eclipse.jdt.core 4 969 2015-07-28 19:14:30.687
!MESSAGE C:\Users\jwg\.p2\pool\plugins\org.codehaus.groovy_2.3.10.xx-201507131633-e45\plugin_dsld_support\ does not exist

!ENTRY org.eclipse.equinox.p2.repository 2 0 2015-07-28 19:15:47.477
!MESSAGE Server returned lastModified <= 0 for https://github.com/openhab/openhab.repo/raw/master/jetty-deps/content.jar

!ENTRY org.eclipse.equinox.p2.repository 2 0 2015-07-28 19:16:55.540
!MESSAGE Server returned lastModified <= 0 for https://github.com/openhab/openhab.repo/raw/master/jetty-deps/artifacts.jar
  
------------ console log -------------------
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.persistence.manager. The reference is: Reference[name = ItemRegistry, interface = org.eclipse.smarthome.core.items.ItemRegistry, policy = dynamic, cardinality = 0..1, target = null, bind = setItemRegistry, unbind = unsetItemRegistry]
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.model.persistence.extensions. The reference is: Reference[name = PersistenceService, interface = org.eclipse.smarthome.core.persistence.PersistenceService, policy = dynamic, cardinality = 0..n, target = null, bind = addPersistenceService, unbind = removePersistenceService]
!MESSAGE Could not bind a reference of component ConfigDescriptionRegistry. The reference is: Reference[name = ConfigDescriptionProvider, interface = org.eclipse.smarthome.config.core.ConfigDescriptionProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addConfigDescriptionProvider, unbind = removeConfigDescriptionProvider]
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.binding.BindingInfoRegistry. The reference is: Reference[name = BindingInfoProvider, interface = org.eclipse.smarthome.core.binding.BindingInfoProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addBindingInfoProvider, unbind = removeBindingInfoProvider]
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.internal.events.OSGiEventManager. The reference is: Reference[name = EventSubscriber, interface = org.eclipse.smarthome.core.events.EventSubscriber, policy = dynamic, cardinality = 0..n, target = null, bind = addEventSubscriber, unbind = removeEventSubscriber]
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.itemregistry. The reference is: Reference[name = StateDescriptionProvider, interface = org.eclipse.smarthome.core.types.StateDescriptionProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addStateDescriptionProvider, unbind = removeStateDescriptionProvider]
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.ThingRegistry. The reference is: Reference[name = ThingProvider, interface = org.eclipse.smarthome.core.thing.ThingProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addProvider, unbind = removeProvider]
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.link.ItemChannelLinkRegistry. The reference is: Reference[name = ItemChannelLinkProvider, interface = org.eclipse.smarthome.core.thing.link.ItemChannelLinkProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addProvider, unbind = removeProvider]
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.type.ThingTypeRegistry. The reference is: Reference[name = ThingTypeProvider, interface = org.eclipse.smarthome.core.thing.binding.ThingTypeProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addThingTypeProvider, unbind = removeThingTypeProvider]
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.link.ItemThingLinkRegistry. The reference is: Reference[name = ItemThingLinkProvider, interface = org.eclipse.smarthome.core.thing.link.ItemThingLinkProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addProvider, unbind = removeProvider]
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.io.rest.root. The reference is: Reference[name = RESTResource, interface = org.eclipse.smarthome.io.rest.RESTResource, policy = dynamic, cardinality = 0..n, target = null, bind = addRESTResource, unbind = removeRESTResource]
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.io.transport.mdns. The reference is: Reference[name = MDNSClient, interface = org.eclipse.smarthome.io.transport.mdns.MDNSClient, policy = dynamic, cardinality = 0..1, target = null, bind = setMDNSClient, unbind = unsetMDNSClient]
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.ui. The reference is: Reference[name = IconProvider, interface = org.eclipse.smarthome.ui.icon.IconProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addIconProvider, unbind = removeIconProvider]
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.io.rest.sitemap. The reference is: Reference[name = SitemapProvider, interface = org.eclipse.smarthome.model.sitemap.SitemapProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addSitemapProvider, unbind = removeSitemapProvider]
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.ui.chart. The reference is: Reference[name = ChartProvider, interface = org.eclipse.smarthome.ui.chart.ChartProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addChartProvider, unbind = removeChartProvider]
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.ui.chart.defaultprovider. The reference is: Reference[name = PersistenceService, interface = org.eclipse.smarthome.core.persistence.PersistenceService, policy = dynamic, cardinality = 0..n, target = null, bind = addPersistenceService, unbind = removePersistenceService]
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.ui.classic.pagerenderer. The reference is: Reference[name = WidgetRenderer, interface = org.eclipse.smarthome.ui.classic.render.WidgetRenderer, policy = dynamic, cardinality = 0..n, target = null, bind = addWidgetRenderer, unbind = removeWidgetRenderer]
!MESSAGE Could not bind a reference of component org.openhab.core.compat1x.actionservicefactory. The reference is: Reference[name = ActionService, interface = org.openhab.core.scriptengine.action.ActionService, policy = dynamic, cardinality = 0..n, target = null, bind = addActionService, unbind = removeActionService]
!MESSAGE Could not bind a reference of component org.openhab.core.compat1x.autoupdateproviderdelegate. The reference is: Reference[name = AutoUpdateBindingProvider, interface = org.openhab.core.autoupdate.AutoUpdateBindingProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addAutoUpdateBindingProvider, unbind = removeAutoUpdateBindingProvider]
!MESSAGE Could not bind a reference of component org.openhab.core.compat1x.bindingconfigreaderfactory. The reference is: Reference[name = BindingConfigReader, interface = org.openhab.model.item.binding.BindingConfigReader, policy = dynamic, cardinality = 0..n, target = null, bind = addBindingConfigReader, unbind = removeBindingConfigReader]
!MESSAGE Could not bind a reference of component org.openhab.core.compat1x.chartproviderfactory. The reference is: Reference[name = ChartProvider, interface = org.openhab.ui.chart.ChartProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addChartProvider, unbind = removeChartProvider]
!MESSAGE Could not bind a reference of component org.openhab.core.compat1x.persistenceservicefactory. The reference is: Reference[name = PersistenceService, interface = org.openhab.core.persistence.PersistenceService, policy = dynamic, cardinality = 0..n, target = null, bind = addPersistenceService, unbind = removePersistenceService]
!MESSAGE Could not bind a reference of component org.openhab.core.compat1x.ttsservicefactory. The reference is: Reference[name = TTSService, interface = org.openhab.io.multimedia.tts.TTSService, policy = dynamic, cardinality = 0..n, target = null, bind = addTTSService, unbind = removeTTSService]

**Comment by kaikreuzer** [comment]
Thanks for the update!
The "Could not bind" messages can indeed be ignored, it's nothing to worry about.
