### ISSUE TITLE
Windows Development: Spaces in Path Keeps Jetty From Loading

### ISSUE THREAD

**Issue by CrackerStealth** [openhab/openhab2#336]
Using the development enviornment in Eclipse under Windows, the jetty server appears to fail to load when the OpenHAB 2 development enviornment is created in any nested path structure that contains spaces. Under my windows enviornment, I had my OpenHAb 2 development enviornment installed in "C:/Users/UserName/My Projects/OpenHAB 2/"  and jetty would fail to load with the following error.

```
2015-08-10 22:42:04 [WARN ] [e.jetty.util.resource.Resource:121  ] - java.net.URISyntaxException: Illegal character in path at index 32: file:/C:/Users/UserName/My Projects/OpenHAB 2/git/openhab2/bundles/io/org.openhab.io.jetty/jettyhome/etc/jetty.xml
2015-08-10 22:42:04 [WARN ] [.o.b.i.s.ServerInstanceWrapper:157  ] - File does not exist file:/C:/Users/UserName/My Projects/OpenHAB 2/git/openhab2/bundles/io/org.openhab.io.jetty/jettyhome/etc/jetty.xml; BadResource=java.net.URISyntaxException: Illegal character in path at index 32: file:/C:/Users/UserName/My Projects/OpenHAB 2/git/openhab2/bundles/io/org.openhab.io.jetty/jettyhome/etc/jetty.xml
java.lang.IllegalStateException: No such jetty server config file: file:/C:/Users/UserName/My Projects/OpenHAB 2/git/openhab2/bundles/io/org.openhab.io.jetty/jettyhome/etc/jetty.xml; BadResource=java.net.URISyntaxException: Illegal character in path at index 32: file:/C:/Users/UserName/My Projects/OpenHAB 2/git/openhab2/bundles/io/org.openhab.io.jetty/jettyhome/etc/jetty.xml
	at org.eclipse.jetty.osgi.boot.internal.serverfactory.ServerInstanceWrapper.configure(ServerInstanceWrapper.java:158)
	at org.eclipse.jetty.osgi.boot.internal.serverfactory.DefaultJettyAtJettyHomeHelper.startJettyAtJettyHome(DefaultJettyAtJettyHomeHelper.java:173)
	at org.eclipse.jetty.osgi.boot.JettyBootstrapActivator.start(JettyBootstrapActivator.java:93)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:936)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:319)
	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
	at org.eclipse.osgi.container.Module.start(Module.java:439)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```

When I deleted everything and restarted from scratch using "C:/Users/UserName/Projects/OpenHAB2/" as the directory (removed all spaces), the development enviornment would run OpenHAB 2 in eclipse with no error and jetty would load correctly.

Related to #72 perhaps.

**Comment by kaikreuzer** [comment]
This is a known problem (see https://github.com/openhab/openhab2/issues/72), for the IDE setup I have now added a note: https://github.com/openhab/openhab2/commit/917a9340cddc5997a8bd4de3e2b27a6589d07f67
