### ISSUE TITLE
AutoApproveService: NPEs

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab2#349]
I got a lot of NPEs from the AutoApproveService.

<pre>
2015-08-21 15:13:41,441 | ERROR | read (Bundle 77) | ds                               | 77 - org.eclipse.equinox.ds - 1.4.200.v20131126-2331 | [SCR] Exception while activating instance org.openhab.core.internal.inbox.AutoApproveService@56698b03 of component org.openhab.autoapprove  
java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.7.0_80]
        at java.lang.reflect.Method.invoke(Method.java:606)[:1.7.0_80]
        at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:235)[77:org.eclipse.equinox.ds:1.4.200.v20131126-2331]
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)[77:org.eclipse.equinox.ds:1.4.200.v20131126-2331]
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)[77:org.eclipse.equinox.ds:1.4.200.v20131126-2331]
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)[77:org.eclipse.equinox.ds:1.4.200.v20131126-2331]
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)[77:org.eclipse.equinox.ds:1.4.200.v20131126-2331]
        at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473)[77:org.eclipse.equinox.ds:1.4.200.v20131126-2331]
        at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217)[77:org.eclipse.equinox.ds:1.4.200.v20131126-2331]
        at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816)[77:org.eclipse.equinox.ds:1.4.200.v20131126-2331]
        at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783)[77:org.eclipse.equinox.ds:1.4.200.v20131126-2331]
        at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89)[77:org.eclipse.equinox.ds:1.4.200.v20131126-2331]
        at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70)[84:org.eclipse.equinox.util:1.0.500.v20130404-1337]
Caused by: java.lang.NullPointerException
        at org.openhab.core.internal.inbox.AutoApproveService.enable(AutoApproveService.java:59)
        at org.openhab.core.internal.inbox.AutoApproveService.activate(AutoApproveService.java:42)
        ... 14 more
</pre>

The reference to the inbox uses <code>policy="dynamic"</code> and <code>cardinality="0..1"</code>.

<pre>
&lt;reference bind="setInbox" cardinality="0..1" interface="org.eclipse.smarthome.config.discovery.inbox.Inbox" name="Inbox" policy="dynamic" unbind="unsetInbox"/&gt;
</pre>

If we would like to kept the reference this way, we must stop using this.inbox without further checks.
Same for thingSetupManager.

The implementation file contains tabs and whitespaces (should be cleaned up).

What is the preferred solution, set policy to static and cardinality to 1 (for thing manager and inbox) or add a check on every usage? IMHO "static and 1" should do the trick, if there is one missing, the service does not need to be activated at all (correct?).

**Comment by kaikreuzer** [comment]
> IMHO "static and 1" should do the trick, if there is one missing, the service does not need to be activated at all (correct?).

Makes sense to me, yes. Fixed with #350, thanks!
