### ISSUE TITLE
Error getting in openhab2

### ISSUE THREAD

**Issue by manivannnan-s** [openhab/openhab2#388]
while i building maven below error i m getting . Give best solution for me . 
Could not find "org.eclipse.smarthome.feature.runtime.core.feature.group/0.8.0.201508140839"

**Comment by kaikreuzer** [comment]
Looks like pretty old source code as it refers to a version from mid August. Please make sure that you build the latest sources.

**Comment by manivannnan-s** [comment]
im working with stable version . But new version getting new errors. can you suggest stable version

**Comment by kaikreuzer** [comment]
Sorry, there is no stable version, only snapshots right now - so to make sure that things compile, always rebase to the latest sources.

**Comment by manivannnan-s** [comment]
i used your latest version through eclipse installer . i got error 

ERROR: org.eclipse.equinox.p2.engine code=4 An error occurred while collecting items to be installed
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:255)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$3.commit(ProfileTransactionImpl.java:523)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:328)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:709)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:2970)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:2900)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:2881)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:2775)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:550)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:635)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
  ERROR: org.eclipse.equinox.p2.engine code=0 session context was:(profile=_home_manivannan_openhab_fresh_openhab_openhab2-master_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 No repository found containing: osgi.bundle,org.eclipse.egit,4.0.2.201509141540-r
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 No repository found containing: osgi.bundle,org.eclipse.egit.core,4.0.2.201509141540-r
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 No repository found containing: osgi.bundle,org.eclipse.egit.doc,4.0.2.201509141540-r
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 No repository found containing: org.eclipse.update.feature,org.eclipse.egit,4.0.2.201509141540-r
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 No repository found containing: org.eclipse.update.feature,org.eclipse.egit.mylyn,4.0.2.201509141540-r
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 No repository found containing: osgi.bundle,org.eclipse.egit.mylyn.ui,4.0.2.201509141540-r
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 No repository found containing: osgi.bundle,org.eclipse.egit.ui,4.0.2.201509141540-r
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 No repository found containing: osgi.bundle,org.eclipse.jgit,4.0.2.201509141540-r
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 No repository found containing: osgi.bundle,org.eclipse.jgit.archive,4.0.2.201509141540-r
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 No repository found containing: org.eclipse.update.feature,org.eclipse.jgit,4.0.2.201509141540-r

**Comment by manivannnan-s** [comment]
Thank you for kind help
