### ISSUE TITLE
Problem with hue lamps

### ISSUE THREAD

**Issue by jrcourtois** [openhab/openhab2#413]
Got another issue with hue lamps now.
I tried with latest .jar and the one I had before (which was working).
org.eclipse.smarthome.binding.hue-0.8.0-20150525.191559-175.jar  
org.eclipse.smarthome.binding.hue-0.8.0-20151008.153112-299.jar

Don't manage to access the list of items (from habmin page, from Paper UI control, or from REST API still the same message in console).

```
2015-10-09 17:50:45 [DEBUG] [io.rest.core.item.ItemResource:127  ] - Received HTTP GET request at 'items'
2015-10-09 17:50:45 [WARN ] [e.jetty.servlet.ServletHandler:620  ] - javax.servlet.ServletException: java.lang.NullPointerException
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:423)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
Caused by: java.lang.NullPointerException: null
	at org.eclipse.smarthome.core.thing.DefaultSystemChannelTypeProvider.getChannelType(DefaultSystemChannelTypeProvider.java:69)
	at org.eclipse.smarthome.core.thing.type.ChannelTypeRegistry.getChannelType(ChannelTypeRegistry.java:67)
	at org.eclipse.smarthome.core.thing.type.TypeResolver.resolve(TypeResolver.java:43)
	at org.eclipse.smarthome.core.thing.type.TypeResolver.resolve(TypeResolver.java:31)
	at org.eclipse.smarthome.core.thing.type.ThingTypeRegistry.getChannelType(ThingTypeRegistry.java:156)
	at org.eclipse.smarthome.core.thing.internal.ChannelStateDescriptionProvider.getStateDescription(ChannelStateDescriptionProvider.java:38)
	at org.eclipse.smarthome.core.items.GenericItem.getStateDescription(GenericItem.java:362)
	at org.eclipse.smarthome.core.items.GenericItem.getStateDescription(GenericItem.java:355)
	at org.eclipse.smarthome.io.rest.core.item.EnrichedItemDTOMapper.map(EnrichedItemDTOMapper.java:47)
	at org.eclipse.smarthome.io.rest.core.item.EnrichedItemDTOMapper.map(EnrichedItemDTOMapper.java:42)
	at org.eclipse.smarthome.io.rest.core.item.EnrichedItemDTOMapper.map(EnrichedItemDTOMapper.java:63)

2015-10-09 17:50:45 [WARN ] [lipse.jetty.server.HttpChannel:395  ] - /rest/items?recursive=truejavax.servlet.ServletException: javax.servlet.ServletException: java.lang.NullPointerException
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:130)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:744)
Caused by: javax.servlet.ServletException: java.lang.NullPointerException
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:423)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
Caused by: java.lang.NullPointerException: null
	at org.eclipse.smarthome.core.thing.DefaultSystemChannelTypeProvider.getChannelType(DefaultSystemChannelTypeProvider.java:69)
	at org.eclipse.smarthome.core.thing.type.ChannelTypeRegistry.getChannelType(ChannelTypeRegistry.java:67)
	at org.eclipse.smarthome.core.thing.type.TypeResolver.resolve(TypeResolver.java:43)
	at org.eclipse.smarthome.core.thing.type.TypeResolver.resolve(TypeResolver.java:31)
	at org.eclipse.smarthome.core.thing.type.ThingTypeRegistry.getChannelType(ThingTypeRegistry.java:156)
	at org.eclipse.smarthome.core.thing.internal.ChannelStateDescriptionProvider.getStateDescription(ChannelStateDescriptionProvider.java:38)
	at org.eclipse.smarthome.core.items.GenericItem.getStateDescription(GenericItem.java:362)
	at org.eclipse.smarthome.core.items.GenericItem.getStateDescription(GenericItem.java:355)
	at org.eclipse.smarthome.io.rest.core.item.EnrichedItemDTOMapper.map(EnrichedItemDTOMapper.java:47)
	at org.eclipse.smarthome.io.rest.core.item.EnrichedItemDTOMapper.map(EnrichedItemDTOMapper.java:42)
	at org.eclipse.smarthome.io.rest.core.item.EnrichedItemDTOMapper.map(EnrichedItemDTOMapper.java:63)

2015-10-09 17:50:45 [WARN ] [lipse.jetty.server.HttpChannel:481  ] - Could not send response error 500: javax.servlet.ServletException: javax.servlet.ServletException: java.lang.NullPointerException

```

**Comment by kaikreuzer** [comment]
Did you upgrade the runtime at the same time?

**Comment by jrcourtois** [comment]
OK, the problem was with my file items/hue.items

```
Group Switching (Lights)

Color Light1 (Switching) { channel="hue:LCT001:001788182930:1:Color" }
Color Light2 (Switching) { channel="hue:LCT001:001788182930:2:Color" }
Color Light3 (Switching) { channel="hue:LCT001:001788182930:3:Color" }

```

**Comment by kaikreuzer** [comment]
Ok, thanks, I have created https://github.com/eclipse/smarthome/pull/487, which should solve the NPE issue.
