### ISSUE TITLE
Problem with historicState function NullPointerException

### ISSUE THREAD

**Issue by mdbergmann** [openhab/openhab2#423]
When a rule triggered which calculates a delta value from an historic state.
This has worked OK in OH1 but not in OH2.
This is the exception stacktrace:

    2015-10-05 09:59:00 [DEBUG] [.o.p.j.i.JpaPersistenceService:192  ] - Retrieving result list...done
    2015-10-05 09:59:00 [DEBUG] [.o.p.j.i.JpaPersistenceService:194  ] - Retrieved 1 items.
    2015-10-05 09:59:00 [DEBUG] [.o.p.j.i.JpaPersistenceService:199  ] - Convert to HistoricItem: 1
    2015-10-05 09:59:00 [ERROR] [.m.r.r.i.engine.ExecuteRuleJob:62   ] - Error during the execution of rule EtaOpHoursWeekjava.lang.NullPointerException: null
    	at java.math.BigDecimal.compareTo(BigDecimal.java:2625)
    	at org.eclipse.smarthome.model.script.lib.NumberExtensions.operator_equals(NumberExtensions.java:170)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:497)
    	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.invokeOperation(XbaseInterpreter.java:1084)
    	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.invokeOperation(XbaseInterpreter.java:1059)
    	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._invokeFeature(XbaseInterpreter.java:1045)
    	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.invokeFeature(XbaseInterpreter.java:990)
    	at org.eclipse.smarthome.model.script.interpreter.ScriptInterpreter.invokeFeature(ScriptInterpreter.java:112)

I'm not exactly certain where the problem is, looking at the code all seems actually fine.

Bit there is a problem somewhere.
One other guy has a problem, too:
https://community.openhab.org/t/problem-with-historicstate-function-nullpointerexception/3054/2

**Comment by kaikreuzer** [comment]
Hm, it seems that this NPE can only happen if there is indeed a null value reached into the comparison function. Could you post your rule where this happens?
I have just tested the historicState() method and it seems to work in general - I was able to get results back from it.
Nonetheless, the NPE should definitely not happen and I have entered a bug at https://bugs.eclipse.org/bugs/show_bug.cgi?id=480804 to fix it.

**Comment by mdbergmann** [comment]
This is the rule.
Replace the minimumSince() with historicState().
minimumSince works, historicState not.
```
rule "EtaIgnitionsWeek"
	Time cron "0 59 23 ? * SUN"
then
	logInfo("EtaIgnitionsWeek", "Last weeks avg ignitions...")
	var previousState = HeatingETAIgnitionCount.minimumSince(now.minusWeeks(1), "jpa").state
	if(previousState == null) {
		logError("Unable to retrieve previous state!")
	} else {
		var diff = HeatingETAIgnitionCount.state - previousState
		var perDay = diff / 7.0
		HeatingETAIgCountPerDay.sendCommand(perDay)
		logInfo("EtaIgnitionsWeek", "Last weeks avg ignitions...done")
	}
end
```

**Comment by kaikreuzer** [comment]
Could you change it for a test to 
```
if(null == previousState)
```
and see if that makes a difference?

**Comment by mdbergmann** [comment]
Hmm, OK. That made a difference.
It's working now. Even though previousState isn't null, when previousState is first in the if clause it's not working.
That's weird.

**Comment by kaikreuzer** [comment]
The NPE is fixed in ESH now and this fix should be available in the upcoming builds of OH2.
So what is most mysterious to me is that the same problem does not occur on OH1 - because the code in question has not been changed at all and looks all identical to me...
