### ISSUE TITLE
Exception in thread "Freeswitch WatchDog" java.lang.IllegalArgumentException: hostname can't be null

### ISSUE THREAD

**Issue by kirantpatil** [openhab/openhab2#426]
I am following, https://github.com/openhab/openhab2/blob/master/docs/sources/installation/runtime.md

I am getting below error in console after starting openhab2 runtime
kpatil  ~  Documents  homeautomation  openhab-2.0.0.alpha2-runtime  ./start.sh
--
Launching the openHAB runtime...
osgi> 2015-10-14 12:44:23.231 [INFO ] [ui.internal.servlet.PaperUIApp] - Started Paper UI at /ui
2015-10-14 12:44:23.740 [WARN ] [b.f.internal.FreeswitchBinding] - Client is not connected, reconnecting
Exception in thread "Freeswitch WatchDog" java.lang.IllegalArgumentException: hostname can't be null
at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149)
at java.net.InetSocketAddress.(InetSocketAddress.java:216)
at org.freeswitch.esl.client.inbound.Client.connect(Client.java:123)
at org.openhab.binding.freeswitch.internal.FreeswitchBinding.connect(FreeswitchBinding.java:215)
at org.openhab.binding.freeswitch.internal.FreeswitchBinding.access$3(FreeswitchBinding.java:207)
at org.openhab.binding.freeswitch.internal.FreeswitchBinding$WatchDog.run(FreeswitchBinding.java:705)
2015-10-14 12:44:24.060 [INFO ] [.u.d.internal.DashboardService] - Started dashboard at /start
2015-10-14 12:44:24.272 [WARN ] [c.inbound.InboundClientHandler] - Unexpected message content type [text/rude-rejection]
2015-10-14 12:44:25.361 [INFO ] [.s.u.c.i.servlet.WebAppServlet] - Started Classic UI at /classicui
2015-10-14 12:44:25.514 [INFO ] [.o.core.internal.CoreActivator] - openHAB runtime has been started (v2.0.0, build alpha2).
freeswitch.conf file content:
--
\#cat conf/services/freeswitch.cfg
\# Host or ip of your freeswitch server
host=172.17.0.1

\# Port that your freeswitch server is listening for ESL connections on
\# (optional, defaults to 8021)
\#port=

\# Password set for ESL connections
password=ClueCon

**Comment by kaikreuzer** [comment]
Please report this at https://github.com/openhab/openhab/issues, since the freeswitch binding sources are in openHAB 1, not here.
